# Generated by Django 5.0.2 on 2025-12-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Aluno"),
                ),
                (
                    "idade",
                    models.PositiveIntegerField(
                        help_text="Idade do Aluno em Anos", verbose_name="Idade"
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Peso do Aluno em Kg",
                        max_digits=5,
                        verbose_name="Peso",
                    ),
                ),
                (
                    "tempo_pratica_meses",
                    models.PositiveIntegerField(
                        help_text="Tempo de prática em meses",
                        verbose_name="Tempo de prática",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atuaizado em"),
                ),
            ],
            options={
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
                "ordering": ["nome"],
            },
        ),
    ]
