# Generated by Django 5.0.2 on 2026-01-02 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aluno", "0001_initial"),
        ("exercicios", "0003_alter_exercicio_difficulty"),
    ]

    operations = [
        migrations.CreateModel(
            name="Treino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("INICIANTE", "Iniciante"),
                            ("INTERMEDIARO", "Intermediario"),
                            ("AVANCADO", "Avancado"),
                        ],
                        max_length=14,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treinos",
                        to="aluno.aluno",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="TreinoExercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("A", "Dia A"),
                            ("B", "Dia B"),
                            ("C", "Dia C"),
                            ("D", "Dia D"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(verbose_name="Ordem no treino"),
                ),
                ("repeticoes", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("series", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "exercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treinos",
                        to="exercicios.exercicio",
                    ),
                ),
                (
                    "treino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercicios",
                        to="treino.treino",
                    ),
                ),
            ],
            options={
                "ordering": ["dia", "ordem"],
            },
        ),
        migrations.AddConstraint(
            model_name="treino",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True)),
                fields=("aluno",),
                name="unique_treino_ativo_por_aluno",
            ),
        ),
        migrations.AddConstraint(
            model_name="treinoexercicio",
            constraint=models.UniqueConstraint(
                fields=("treino", "dia", "exercicio"),
                name="unique_exercicio_por_dia_no_treino",
            ),
        ),
    ]
