# Generated by Django 5.0.2 on 2025-12-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treino", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="treinoexercicio",
            name="repeticoes",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name="treinoexercicio",
            name="series",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name="treino",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("INICIANTE", "Iniciante"),
                    ("INTERMEDIARO", "Intermediario"),
                    ("AVANCADO", "Avancado"),
                ],
                max_length=14,
            ),
        ),
    ]
