# Generated by Django 5.0.2 on 2025-12-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="ID do exercicio no ExerciseDB",
                        max_length=50,
                        unique=True,
                        verbose_name="ID Externo",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome do Exercicio"),
                ),
                (
                    "target",
                    models.CharField(max_length=100, verbose_name="Músculo Alvo"),
                ),
                (
                    "secondary_muscles",
                    models.JSONField(default=list, verbose_name="Musculos Secundários"),
                ),
                (
                    "body_part",
                    models.CharField(max_length=100, verbose_name="Parte do corpo"),
                ),
                (
                    "equipament",
                    models.CharField(max_length=100, verbose_name="Equipamento"),
                ),
                ("category", models.CharField(max_length=50, verbose_name="Categoria")),
                (
                    "difficulty",
                    models.CharField(max_length=50, verbose_name="Dificuldade"),
                ),
                (
                    "instruction",
                    models.JSONField(default=list, verbose_name="Instruções"),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                ("gif_url", models.URLField(verbose_name="Gif do Exercicio")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Exercício",
                "verbose_name_plural": "Exercícios",
                "ordering": ["name"],
            },
        ),
    ]
