# Generated by Django 5.0.2 on 2025-12-31 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercicios", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercicio",
            old_name="equipament",
            new_name="equipment",
        ),
        migrations.RenameField(
            model_name="exercicio",
            old_name="instruction",
            new_name="instructions",
        ),
    ]
