# Generated by Django 5.0.2 on 2026-01-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercicios", "0002_rename_equipament_exercicio_equipment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercicio",
            name="difficulty",
            field=models.IntegerField(
                choices=[(1, "Iniciante"), (2, "Intermediário"), (3, "Experiente")],
                verbose_name="Nível do Exercício",
            ),
        ),
    ]
